### ISSUE TITLE
Update android sample

### ISSUE THREAD

**Issue by headupinclouds** [headupinclouds/ogles_gpgpu#3]
- Move camera to a separate thread (http://stackoverflow.com/questions/27626002/camera-preview-using-surface-texture; http://stackoverflow.com/a/19154438 (sample implementation)) outside of the UI main thread
- Use the Camera2 API (more features)  : https://github.com/googlesamples/android-Camera2Basic

```
This project uses the old, deprecated "Camera" API but therefore still runs on older Android systems than 5.0 "Lollipop". Using the Camera2 API should work in a similar way.  Android systems than 5.0 "Lollipop". Using the Camera2 API should work in a similar way.
```

cc: @ruslo

**Comment by ruslo** [comment]
> cc: @ruslo

not needed, I'm in watchers already
